"""initial schema

Revision ID: 84e0d6b0ebbf
Revises: 
Create Date: 2026-06-17 22:44:30.656010

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '84e0d6b0ebbf'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('extractions',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('raw_input', sa.Text(), nullable=False),
    sa.Column('input_type', sa.String(length=20), nullable=False),
    sa.Column('merchant', sa.String(length=255), nullable=True),
    sa.Column('amount', sa.Float(), nullable=True),
    sa.Column('currency', sa.String(length=10), nullable=True),
    sa.Column('purchase_date', sa.Date(), nullable=True),
    sa.Column('subscription_status', sa.String(length=20), nullable=True),
    sa.Column('renewal_date', sa.Date(), nullable=True),
    sa.Column('free_trial_end_date', sa.Date(), nullable=True),
    sa.Column('return_deadline', sa.Date(), nullable=True),
    sa.Column('warranty_end_date', sa.Date(), nullable=True),
    sa.Column('cancellation_policy', sa.Text(), nullable=True),
    sa.Column('refund_opportunity', sa.Text(), nullable=True),
    sa.Column('price_increased', sa.Boolean(), nullable=True),
    sa.Column('old_price', sa.Float(), nullable=True),
    sa.Column('new_price', sa.Float(), nullable=True),
    sa.Column('confidence_score', sa.Float(), nullable=True),
    sa.Column('field_confidences', sa.Text(), nullable=True),
    sa.Column('raw_llm_response', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('action_cards',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('extraction_id', sa.String(length=36), nullable=False),
    sa.Column('action_type', sa.String(length=30), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('urgency', sa.String(length=10), nullable=False),
    sa.Column('deadline', sa.Date(), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['extraction_id'], ['extractions.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('email_drafts',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('action_card_id', sa.String(length=36), nullable=False),
    sa.Column('subject', sa.String(length=500), nullable=False),
    sa.Column('body', sa.Text(), nullable=False),
    sa.Column('user_edited_body', sa.Text(), nullable=True),
    sa.Column('copied', sa.Boolean(), nullable=False),
    sa.Column('raw_llm_response', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['action_card_id'], ['action_cards.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('action_card_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('email_drafts')
    op.drop_table('action_cards')
    op.drop_table('extractions')
    # ### end Alembic commands ###
